[build-system]
requires = ["setuptools>=42", "wheel", "pybind11~=2.11.1"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "serial",
]

[tool.cibuildwheel]
skip = "pp*"