name: Test the library on multiple OS

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        # - macos-13 # macos not supporte
        # - macos-14 # macos not supporte
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: setup python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Build library
        run: pip install .
      - name: Install test dependencies
        run: pip install -r requirements-test.txt
      - name: Show installed dependencies
        run: pip freeze
      - name: Run tests
        run: pytest -vv -k "not slow"